import type { Metadata } from "next";
import "./globals.css";
import StoreProvider from "@/common/components/StoreProvider";

export const metadata: Metadata = {
  title: "Todo App",
  description: "Generated by Max Martinez",
  icons: {
    icon: "/astro.png"
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <StoreProvider>
        <body>
          <main className="md:w-[75%] xl:w-[45%] mx-auto p-4">
            {children}
          </main>
        </body>
      </StoreProvider>
    </html>
  );
}
